// swift-tools-version: 6.0
import PackageDescription

// PackTrace: local macOS collection app. Core (domain, storage, catalog, images)
// is a library so tests and the UI share one implementation and the UI never
// touches SQLite or the RNG directly.
let package = Package(
    name: "PackTrace",
    platforms: [.macOS(.v14)],
    products: [
        .executable(name: "PackTrace", targets: ["PackTraceApp"]),
        .executable(name: "packtrace-catalog", targets: ["PackTraceCatalogTool"]),
        .library(name: "PackTraceCore", targets: ["PackTraceCore"]),
        .library(name: "PackTraceUI", targets: ["PackTraceUI"]),
    ],
    targets: [
        .target(
            name: "PackTraceCore",
            resources: [
                .copy("Resources/catalog"),
                .copy("Resources/pool"),
                .copy("Resources/pack-artwork"),
            ]
        ),
        .executableTarget(
            name: "PackTraceCatalogTool",
            dependencies: ["PackTraceCore"]
        ),
        // Views, view models and app environment live in a library so the
        // opening/exchange flow can be driven headlessly from tests. Bundle
        // metadata lives in packaging/Info.plist and is applied by
        // scripts/make-app-bundle.sh; SwiftPM does not accept Info.plist as a
        // target resource.
        // Opening sound cues are original files generated by
        // scripts/generate-opening-sounds.py.
        .target(
            name: "PackTraceUI",
            dependencies: ["PackTraceCore"],
            resources: [
                .copy("Resources/sounds"),
            ]
        ),
        // Test-only helpers: shared OMP log fixtures and error capture. Not a
        // package product, so it never ships with the app.
        .target(
            name: "PackTraceTestSupport",
            dependencies: ["PackTraceUI"]
        ),
        .executableTarget(
            name: "PackTraceApp",
            dependencies: ["PackTraceUI", "PackTraceCore"]
        ),
        .testTarget(
            name: "PackTraceCoreTests",
            dependencies: ["PackTraceCore", "PackTraceTestSupport"]
        ),
        .testTarget(
            name: "PackTraceUITests",
            dependencies: ["PackTraceUI", "PackTraceCore", "PackTraceTestSupport"]
        ),
    ]
)
